### ISSUE TITLE
Audio/Video received doesn't play

### ISSUE THREAD

**Issue by juanjotoronja** [Sytten/Facebook-Messenger-Desktop#1]
Keeps loading but nothing happens, but if i enter to the web it plays both of them.

**Comment by Sytten** [comment]
It's a new problem from my updates or you had that problem before?

**Comment by juanjotoronja** [comment]
I've started using this messenger for desktop yesterday, i've installed your version because of the fixes like start minimized on startup and still active for updates. Also the video not playing was reported to the original developer, can you check both Audio/Video at least for me none of them are working in the application but plays normally in the browser. Thanks

**Comment by Sytten** [comment]
Just checked and I have the same problem. I will check what I can do. My guess is maybe its an old version of chromium running and it doesnt support the HTML5. If thats the case then its easy to fix, otherwise it will need further investigation...

**Comment by juanjotoronja** [comment]
Thanks, keep it up :)

**Comment by Sytten** [comment]
Ok I got time to check the problem. My opinion is that its a framework based problem. Now, they released yesterday a beta of a new version of NWJS. Many changes occurred in the framework, but I will try to migrate the app tomorrow. It should resolve the issue.

**Comment by Sytten** [comment]
NWJS doesnt support it for the moment, so cant do much about it.
