### ISSUE TITLE
investigate basing work off of whatsie

### ISSUE THREAD

**Issue by terinjokes** [Sytten/Facebook-Messenger-Desktop#12]
Starting an issue here to keep track of anyone else interested in helping me work on a messenger built on whatsie.

I don't know if we want to work on it as a branch here, or as a new line of code. I'm happy to start a new repo in the later case.

**Comment by Sytten** [comment]
For records:

SYTTEN:
Actually, he is currently working on Whatsie (https://github.com/Aluxian/Whatsie) which is a wrapper for whatsapp based on electron. His code is much more mature than this one and will be easy transferred to facebook-messenger. I don`t really want to do a release only this specific bug, so I will wait until I have more stuff to push.
If you guys are motivated, the best thing to do would be to help finish the app whatsie and then make the changes necessary to use messenger instead.
Another possibility would be to continue maintaining this code and update NWJS, but I think that electron is a more mature framework and, lets be honest, this code is a total mess right now...

TERIN:
@Sytten completely off topic (sorry!), but I can start a branch based on whatsie. Either based on yours, or based on upstream.

SYTTEN:
I know its off topic, but I will clean it later. If you have more experience with electron, I suggest your fork the whatsie app and start working on it.
Actually the app is almost finished from what we talked on gitter:
" What's left to do: updates, keyboard shortcuts annddd well, that's pretty much it except some fixes and eventual bugs/issues from gh "
So my plan would be:
1- Fork whatsie
2- Finish the work to complete the app
3- Create a new repo based on the work of whatsie
4- Change the code in that repo to use messenger instead

**Comment by terinjokes** [comment]
@Sytten sorry, I must have created this issue as you were replying. Thanks for cleaning up the original issue and copying the thread here. :+1: 

---

We also want keyboard shortcuts here (see #10) so adding that to whatsie is going to be inevitable. Good place for me to start in the fork.

**Comment by Sytten** [comment]
Any development so far? I will have time next weekend to work on that

**Comment by Sytten** [comment]
Not relevant anymore
