### ISSUE TITLE
Icon disappears, high CPU usage

### ISSUE THREAD

**Issue by tsbarnes** [Sytten/Facebook-Messenger-Desktop#14]
I'm using the Unity desktop on Ubuntu 15.10.

A second or two after the app starts, the icon disappears from the panel and my CPU usage increases at least 25% on all four of my CPU cores.  The CPU usage doesn't go back down until I kill the Messenger process, and if I leave the process running, the icon occasionally flashes back into the panel for less than a second then disappears again.

While the CPU usage is high, it's the Messenger process, Compiz, and the panel are all using high amounts of CPU.

**Comment by Sytten** [comment]
Hey can you try to change the exec line in the desktop file:
Exec=env XDG_CURRENT_DESKTOP=GNOME /opt/MessengerForDesktop/Messenger

**Comment by Sytten** [comment]
The best solution I have is to use a new system tray app:
http://www.webupd8.org/2015/05/on-demand-system-tray-for-ubuntu.html
