### ISSUE TITLE
Thank you for this fork

### ISSUE THREAD

**Issue by MakuSensei** [Sytten/Facebook-Messenger-Desktop#15]
thank you've done this fork is a shame that the original developer abandoned beyond this application :/

Also I recommend Native Fier
You do a web app versions
You can use nativefier you to create a Facebook Messenger app and take some parts of the code to improve aluxian

[https://github.com/jiahaog/nativefier](https://github.com/jiahaog/nativefier)

**Comment by Sytten** [comment]
Thanks ;)
Currently I don`t have a lot of time, but as said in other issues, a new version based on electron is in development by the original dev. Its called Whatsie (its a repo on the original dev) for whatsapp, but it would be easy to convert it for facebook messenger. Eventually I might do it, but with school I currently dont have enough time. 
Cheers
