### ISSUE TITLE
Chat box is white regardless of theme

### ISSUE THREAD

**Issue by Kezarious** [Sytten/Facebook-Messenger-Desktop#17]
The box where you type new messages is white, regardless of which theme I use. Makes the dark and mosaic themes hard to use, since their message font is white... 

I had this problem with the dev's version which is why I tried switching to yours. I've no idea why it's happening, but if you could investigate, that'd be great. :)

**Comment by Sytten** [comment]
Thats strange, I need more info. What os do you use?
Can you provide a screenshot?

**Comment by Kezarious** [comment]
I'm using Linux Mint Cinnamon 17.3
Here's a screenshot:
![sceenshot](https://cloud.githubusercontent.com/assets/6114571/13330925/0f49825a-dbf3-11e5-97b1-8e72037ae4e5.png)

**Comment by Sytten** [comment]
I see its just a small CSS problem, I will try to do a release this weekend.

**Comment by Sytten** [comment]
Ok it is fixed, I will release new executable later today.
