### ISSUE TITLE
Many Messenger.exe process running at once

### ISSUE THREAD

**Issue by juanjotoronja** [Sytten/Facebook-Messenger-Desktop#2]
I'm on Windows 7 x64 and everytime messenger runs at startup or even executed manually there is 3 messenger.exe *32 running at the same time.

**Comment by Sytten** [comment]
Is it a new thing from my updates? I think its the way the framework used works...

**Comment by juanjotoronja** [comment]
Don't know, think i read about this behavior reported as an issue to the original developer, the three process use different memory less than 60 KB.

**Comment by Sytten** [comment]
Yea just checked, I'm pretty sure its a normal behaviour of the current framework. The V2.0 will be written with a new framework. I think that when you see 3 processes with the same name, you have in fact a chromium process, a nodejs process and the actual app (not sure about that, just guessing).

**Comment by juanjotoronja** [comment]
Thanks for the feedback
