### ISSUE TITLE
Bug system tray icon

### ISSUE THREAD

**Issue by evgenitsn** [Sytten/Facebook-Messenger-Desktop#20]
SIze of the icon does not fit properly.
![snapshot1](https://cloud.githubusercontent.com/assets/7677924/13524388/93f920b2-e203-11e5-8dba-123d2288596a.png)

Also if I click on it, the app does not show. I have to right-click it then Show Messenger.

**Comment by Sytten** [comment]
Update your plasma to 5.5 this is a known issue already resolved. 
As for the other problem it is also a trouble with the old plasma and I can't do much about it.

**Comment by evgenitsn** [comment]
As I see, my plasma version is **5.5.4**
![image](https://cloud.githubusercontent.com/assets/7677924/13532986/01a2ade4-e237-11e5-857b-466decd07303.png)

**Comment by Sytten** [comment]
With the new version of plasma they restored the support for old tray icon and its working perfectly out of the box on openSuse with the latest plasma 5.5.4 here. So guess would be that you used  libappindicator1 or something like that and it's still used despite the new system. See this PR for more information: https://github.com/Sytten/Facebook-Messenger-Desktop/pull/8

**Comment by cassiodoroVicinetti** [comment]
@evgeni-tsn What does `plasmashell --version` output?

**Comment by evgenitsn** [comment]
```
~$ plasmashell --version
plasmashell 5.5.4
```

**Comment by Sytten** [comment]
I really dont know what to say, it works well on my system with the same KDE version...
During the time they dropped support for the legacy tray, did you use another system like libindicator? That might be a source of conflict...
