### ISSUE TITLE
Firefox drag and drop image crashes app

### ISSUE THREAD

**Issue by Majki** [Sytten/Facebook-Messenger-Desktop#24]
If I drag and drop image from any other app, it uploads correctly. Bur if Firefox used - crashes the app. 

Ubuntu 14.04 64bit

**Comment by Sytten** [comment]
Everybody seems to have problem on Ubuntu lol.
Really I have not idea what to do, the app doesn't even handle the drag and drop. It's all done by the chromium browser. Remember that this is just a wrapper.

**Comment by Majki** [comment]
What's interesting, other apps work flawless - I can drag and drop pics from them.

**Comment by Sytten** [comment]
Try with the latest version, I tested and its not crashing
