### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by mrrs6** [Sytten/Facebook-Messenger-Desktop#32]
I've been trying to fix it, but i've been unable to compile it successfully.
When no internet connection is available window keeps re-appearing and you just cant do anythings besides closing it, the only solution i found is to kill all its processes manually.

**Comment by Sytten** [comment]
I know, the best option would be to implement a counter of connection and close automatically after a number X of times it fails...

**Comment by mrrs6** [comment]
I haven't had a chance since this issue report, but i'm still trying to 
compile it.
Once i'm able to run it from source, i'll fix this and make a quick guide :)

Thanks,
Jose

**Comment by Sytten** [comment]
Many people posted about that, you can take a look here:
https://github.com/Sytten/Facebook-Messenger-Desktop/pull/8#issuecomment-168807293

**Comment by Sytten** [comment]
Try the new release :)
