### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by s-k-y-l-i** [Sytten/Facebook-Messenger-Desktop#33]
Emojis are missing :s I have to check on web to be able to see my friends faces.
![image](https://cloud.githubusercontent.com/assets/7442913/14351545/3c71b9fc-fcd0-11e5-9076-e52e41adbdcf.png)

**Comment by Sytten** [comment]
This is kind of strange... Can you check on messenger.com that they are in fact there?

**Comment by s-k-y-l-i** [comment]
I don't know what happend but they are working now :o maybe facebook fixed it :) 
![image](https://cloud.githubusercontent.com/assets/7442913/15774234/9d53837c-297b-11e6-8e95-3ed7f44448d8.png)
