### ISSUE TITLE
Building on Arch Linux

### ISSUE THREAD

**Issue by fusion809** [Sytten/Facebook-Messenger-Desktop#34]
Hi,

I was wondering how one would compile this project's source code on Arch Linux. I know I could install this program by writing a PKGBUILD that uses official Debian or RPM releases of this project, but I want to compile this program's source code and then install this program from said compiled source code. 

Thanks for your time,
Brenton

**Comment by Sytten** [comment]
This should be quite easy, many people seemed to have problem building from source (I didnt), you can take a look here to start:
https://github.com/Sytten/Facebook-Messenger-Desktop/pull/8#issuecomment-168807293
If you build for arch I would be very happy to have the result!

**Comment by Sytten** [comment]
Can you check that https://github.com/Sytten/Facebook-Messenger-Desktop/pull/35

**Comment by efournival** [comment]
Hello, are you aware of this:
https://aur.archlinux.org/packages/messengerfordesktop-git/

**Comment by Sytten** [comment]
Yes thank you

**Comment by MarcinWieczorek** [comment]
MFD builds like a charm on ArchLinux and the package mentioned above proves it.
This issue can be closed imho.

**Comment by Sytten** [comment]
Most Arch users seems to want to compile on their own to be able to customize the software so I don't think I will provide official builds.
