### ISSUE TITLE
Causes very high Compiz / unity-panel-service CPU usage

### ISSUE THREAD

**Issue by hotice** [Sytten/Facebook-Messenger-Desktop#36]
The application causes a very high Compiz / unity-panel-service CPU usage - see screenshot: http://i.imgur.com/lFZsfUc.png

Also, the tray icon is missing (it shows up and then disappears for a few times when I start the app, then it never shows up again) in Ubuntu - screenshot: http://i.imgur.com/nJsDQIM.png

Tested with Ubuntu 16.04 (64bit).

**Comment by hotice** [comment]
By the way, this issue occurred with the original Facebook-Messenger-Desktop a while back too: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/65 but it was later fixed.

**Comment by Sytten** [comment]
Think we found the problem according to this PR https://github.com/Aluxian/Facebook-Messenger-Desktop/pull/402

**Comment by Sytten** [comment]
Will fix it this weekend
