### ISSUE TITLE
Change text color on mosaic theme

### ISSUE THREAD

**Issue by carlosflorencio** [Sytten/Facebook-Messenger-Desktop#38]
Hi,

Can you change the text color to white of this right area?

![image](https://cloud.githubusercontent.com/assets/1500881/15114136/6154c8b6-15f0-11e6-8156-ee6a90f78062.png)

Thanks

**Comment by Sytten** [comment]
Yes it should be easy, will try to do that during the next weekend...

**Comment by carlosflorencio** [comment]
Many thanks

**Comment by Sytten** [comment]
Done https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/6df9a5e857c5a5befd2c071f65b758dabb643fe5
