### ISSUE TITLE
Inherit chat color options in the dark theme + font color choice

### ISSUE THREAD

**Issue by rikai** [Sytten/Facebook-Messenger-Desktop#40]
Currently, the dark theme doesn't appear to inherit the chat colors while the mosiac theme does, would be nice to see support for this in the dark theme as well.

As a secondary, somewhat related request, i'd also like to see the abiity to choose my local font colors for chats, as white/black are not always readable with certain chat background colors.

**Comment by Sytten** [comment]
I have to work on the themes for other reasons, I will do that at the same time.
Thanks for reporting!

**Comment by s-k-y-l-i** [comment]
it's merged to the develop branch
