### ISSUE TITLE
Credits & License

### ISSUE THREAD

**Issue by Sytten** [Sytten/Facebook-Messenger-Desktop#42]
It would be a good idea to include me and @nevercast as main contributors.
We should also give credit to the community, because they made some good fixes!

Also I would see if we should not change our license to GPL, because I think MIT is too permissive. It was brought to my attention that some people might use our work to create paid and closed-source applications without giving credits...
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/391

**Comment by terinjokes** [comment]
The MIT license requires attribution. If they're going to use your work to create a commercial product, they're going to do so even as GPL.
