### ISSUE TITLE
Messenger doesn't load in Ubuntu Mate 16.04 64bit

### ISSUE THREAD

**Issue by 19darion91** [Sytten/Facebook-Messenger-Desktop#46]
A couple of days ago i tried launching the app while I lacked internet connection (miss-clicked on the shortcut). From that point on after I launch the app it renames the window to "app.html" and doesn't load. When I open the DevTools i get this error "Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR - http://www.messenger.com/login".
Tried reinstalling the app and also tried installing Aluxian's version - to no avail. The problem persists and makes the app unusable. 
Please help!

**Comment by Majki** [comment]
Confirming on Mint 17.

**Comment by Sytten** [comment]
Mint is working, I used for more than a year. 
Try deleting the cache and config folders (in the home folder under .cache and .config).

**Comment by Majki** [comment]
Removed .config, could not locate messenger's cache in .cache folder :(

**Comment by Sytten** [comment]
And I suppose its not working?

**Comment by Sytten** [comment]
Ok see that please: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/453

**Comment by Sytten** [comment]
Should be fixed with latest version :)
