### ISSUE TITLE
[RHEL 6.7] can't open libnotify.so.4

### ISSUE THREAD

**Issue by toanqc** [Sytten/Facebook-Messenger-Desktop#47]
I'm getting this error after installing the RPM both 32bit and 64bit package on Redhat 6.7

/opt/MessengerForDesktop/Messenger: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

Anyidea how to fix it

**Comment by Sytten** [comment]
Probably a dependency not installed on your computer... I will try to investigate if I have time.

**Comment by Sytten** [comment]
Have you tried something else? I tested on a fresh openSuse and its working fine.

**Comment by toanqc** [comment]
I'm not sure what should I try. I think there will be a problem with CentOS 6.7 too. I tried to google the error but didn't find the solution.

**Comment by Sytten** [comment]
@cassiodoroVicinetti Can you help me here, not very used with non-debian systems.

@toanqc you might also want to test the beta I launch on the official repo: https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.5.0-beta.0

**Comment by cassiodoroVicinetti** [comment]
@Sytten  Sorry, I'm not used with non-Debian systems too.

**Comment by toanqc** [comment]
@Sytten : Thank you
I tried to install the version you gave. Look like the original issue gone. But now got another problem with others libraries:

> /opt/MessengerForDesktop/Messenger: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /opt/MessengerForDesktop/lib/libnw.so)
> /opt/MessengerForDesktop/Messenger: /usr/lib64/libstdc++.so.6: version`CXXABI_1.3.5' not found (required by /opt/MessengerForDesktop/lib/libnw.so)
> /opt/MessengerForDesktop/Messenger: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /opt/MessengerForDesktop/lib/libnw.so)

I think this problem is because of the version of RedHat 6.7 / CentOS 6.7 since it won't happen with the newest version 7. I also was trying to fix this problem in other software but unfortunately there is no-safe way to do this. I don't know if you can't do anything from your side then we can close this issue I think.

Thank you for your work! I'm very appreciate that.

**Comment by Sytten** [comment]
Sorry I have little power over the libraries used by the application. 
Everything is handled by NWJS and the underlined chromium browser...

At least you can make it work on the v7. If you have other problems I suggest you post on the official repo from now on since I'm the maintainer now and you would have more chance to have help from other linux rpm users ;)
