### ISSUE TITLE
Performance Issue Ubuntu 16.04

### ISSUE THREAD

**Issue by rrmina** [Sytten/Facebook-Messenger-Desktop#49]
Version: 1.4.7
OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Just open MFD

I noticed that when MFD is open, compiz and unity-panel-service start to eat most of the CPU.
![screenshot from 2016-07-16 15-11-26](https://cloud.githubusercontent.com/assets/7788765/16893349/9efab4da-4b67-11e6-9c85-4c13735ecadd.png)

I didn't experience this problem with v1.4.3

**Comment by rrmina** [comment]
By the way, it isn't mac. It's ubuntu with mac theme :) . 

Also notice that there's a bug with the tray. It isn't showing the correct icon.

**Comment by Sytten** [comment]
I now am the official maintainer of the app, my fork is not updated anymore.
You can switch back to the official repo and test my latest beta.
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.5.0-beta.1

**Comment by Sytten** [comment]
The performances should be better now. But its not perfect, I'm still working on it!

**Comment by Sytten** [comment]
https://github.com/Sytten/Facebook-Messenger-Desktop/issues/25
