### ISSUE TITLE
Payments feature doesn't work

### ISSUE THREAD

**Issue by Sytten** [Sytten/Facebook-Messenger-Desktop#5]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/305

**Comment by terinjokes** [comment]
![](https://share.terinstock.com/2015-12-31_23-50-41.png)

This feature works here, but I already have a payment profile setup on Facebook. Is it kicking poeple back to Facebook that don't already have a payment profile?

---

My friend is probably confused as to why I randomly sent him $1.

**Comment by Sytten** [comment]
Not sure, the original post is vague... I will try myself as I don't have a payment profile
