### ISSUE TITLE
UPDATE ABOUT THE FORK

### ISSUE THREAD

**Issue by Sytten** [Sytten/Facebook-Messenger-Desktop#52]
Hey!
First, sorry guys I kind of left the fork for dead for some time.
I worked on the official repo of Facebook Messenger, but since the owner wants to make the move to Electron with a new V2 I will continue to develop the software here.
I'm currently merging my changes to deploy a new stable version soon (tomorrow).

This version might contain some new bugs, I will try to fix them quick and then go on a monthly based release maybe with beta between them. All further development will be on the develop branch and the master will only contain stable code.

Thanks for your support!

**Comment by Sytten** [comment]
Its done! Please enjoy and reported bugs/suggestions here!

**Comment by Kezarious** [comment]
Hi! Thanks for the update and all the work you've done so far. One possible bug I've noticed is themes don't seem to be working in the new update. I right click as usual on a chat window to bring up the menu, but nothing happens. I'm not sure if this is intentional, and/or the theme options might have been moved elsewhere...

**Comment by Sytten** [comment]
Yes its been moved to the tray icon menu.
Right click on the tray icon and you should see the new menu (with the themes under Visual).
Cheers!

**Comment by Kezarious** [comment]
Oh I found it. Thanks!

**Comment by snj33v** [comment]
Any major features will missing from new V2?, just asking

**Comment by Sytten** [comment]
Well, for the moment there are more features in this version (and its more stable)
I don't have much time to work on it since I now work full time, so maybe in the future the V2 will just be better and so we will switch.
