### ISSUE TITLE
Cannot change themes after the update

### ISSUE THREAD

**Issue by PaskoZhelev** [Sytten/Facebook-Messenger-Desktop#54]
Hello!

First of all thanks for this amazing fork. 

I have updated to version 1.5.0 but now I can't change the themes. I was using Dark theme but now it comes directly with the White one and I cannot change it.

**Comment by PaskoZhelev** [comment]
UDATE

I found it! You have to right click the icon in the task bar and from the Visual menu you can change it. Previously, it was with right clicking the chat itself. 

Anyway, this issue is solved! :)

**Comment by Sytten** [comment]
Yes I found that right click on chat should only be for Copy/Paste options :)

**Comment by tenzanoni** [comment]
err, how could i change it in ubuntu @Sytten ? Right click not working anymore

**Comment by Sytten** [comment]
What do you mean not working?

**Comment by tenzanoni** [comment]
In ur previous ver, i still can right click to change theme, reload, autohide. But in current ver, right click show nothing. Dunno how to change theme anymore :-s

**Comment by Sytten** [comment]
PaskoZhelev commented on Sep 1

UDATE

I found it! You have to right click the icon in the task bar and from the Visual menu you can change it. Previously, it was with right clicking the chat itself.

Anyway, this issue is solved! :)

**Comment by tenzanoni** [comment]
i thought it's solution for windows =)))
ubuntu has no taskbar, bruh :-s

**Comment by Sytten** [comment]
you can install a software to make it available again.
Ubuntu deprecated their, but alternative exists.
Beside dont use Unity, its crappy :D
