### ISSUE TITLE
error the 2.01 not working

### ISSUE THREAD

**Issue by cabban** [Sytten/Facebook-Messenger-Desktop#60]
![error](https://cloud.githubusercontent.com/assets/19514493/19408332/7b334040-92ba-11e6-992e-3adc9835d728.jpg)

@Sytten  i got only a message says new 2.02 is here , but nothing happen. install 2.01 this message is coming , 
![error](https://cloud.githubusercontent.com/assets/19514493/19408334/a006f7fe-92ba-11e6-957f-c4579d93902a.jpg)

**Comment by Sytten** [comment]
Well I don't maintain the 2.0.1 software. My versions stops at v1.5.0.
Did you install the latest from the official dev?

**Comment by cabban** [comment]
@Sytten your fork is working perfectly i remoe this issue now. yes from official dev yes _:)
