### ISSUE TITLE
After update sidebar collapses at half my resolution

### ISSUE THREAD

**Issue by ghost** [Sytten/Facebook-Messenger-Desktop#61]
**Details**
- OS: Windows 7
- Screen Resolution: 1366x768

A few versions ago I was able to view the full sidebar when I drag the application window to the sides causing it to resize to half the width of the screen.

Now when I do this the sidebar is collapsed. My main problem with this is that when I want to select the 'Active Facebook Friends' option, it is no longer immediately available in the sidebar. I have to resize it to slightly larger than half of my screen width in order to reveal the gear/cog icon which contains the other settings.

![a](https://cloud.githubusercontent.com/assets/8528269/19608449/0dff1978-9804-11e6-9252-21e30bcbd585.JPG)

![untitled](https://cloud.githubusercontent.com/assets/8528269/19608457/22e82dc0-9804-11e6-964a-f5d9fa380f94.png)

**Comment by Sytten** [comment]
Yep it bugs me too, its facebook fault though.
It probably just a CSS adjustment, I will check it out this weekend.
I needed to do a release soon anyway :)

**Comment by Sytten** [comment]
Its fixed in the dev branch, it will be in the next release
